[package]
name = "binary_tree"
version = "0.1.0"
authors = ["Vladislav Maltsev <malcev@azoft.com>"]

[lib]
name = "geometry"
path = "src/geometry.rs"

[[bin]]
name = "formating"
path = "src/formating.rs"

[dependencies]

rand = "0.3.16"
num = "0.1.40"